import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Navbar from "./Navbar";

const About = () => {
  const navigate = useNavigate();

  // Scroll to top on mount
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen w-full bg-gradient-to-br from-[#C084FC] via-[#A855F7] to-[#7E22CE] font-['Outfit',sans-serif]">
      {/* Desktop Header */}
      <header className="hidden md:flex items-center justify-between px-8 lg:px-16 pt-6 pb-4">
        <button
          onClick={() => navigate("/")}
          className="flex items-center gap-2"
        >
          <img
            src="/static/quizethic-favicon.svg"
            alt="Quizethic AI Logo"
            className="w-10 h-10 rounded-xl"
          />
          <span className="font-bold text-lg text-white drop-shadow">
            Quizethic AI
          </span>
        </button>
        
        {/* Center Navigation */}
        <Navbar />
        
        <button
          onClick={() => navigate(-1)}
          className="p-2 text-white/80 hover:text-white transition-colors"
        >
          <svg
            className="w-6 h-6"
            fill="none"
            stroke="currentColor"
            strokeWidth={2}
            viewBox="0 0 24 24"
          >
            <path d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </header>

      {/* Mobile Header */}
      <header className="md:hidden flex items-center justify-between px-5 pt-6 pb-4">
        <button
          onClick={() => navigate("/")}
          className="flex items-center gap-2"
        >
          <img
            src="/static/quizethic-favicon.svg"
            alt="Quizethic AI Logo"
            className="w-8 h-8 rounded-xl"
          />
          <span className="font-bold text-base text-white drop-shadow">
            Quizethic AI
          </span>
        </button>
        <button
          onClick={() => navigate(-1)}
          className="p-2 text-white/80 hover:text-white transition-colors"
        >
          <svg
            className="w-6 h-6"
            fill="none"
            stroke="currentColor"
            strokeWidth={2}
            viewBox="0 0 24 24"
          >
            <path d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </header>

      {/* Main Content */}
      <main className="px-5 pb-8">
        {/* Hero Section */}
        <section className="mt-6 mb-8">
          <h1 className="text-3xl font-bold text-white mb-3">
            About Quizethic AI
          </h1>
          <p className="text-white/80 text-base leading-relaxed">
            Your AI-powered companion for smarter exam preparation.
          </p>
        </section>

        {/* Mission Card */}
        <section className="mb-6">
          <div className="bg-white/15 backdrop-blur-md rounded-2xl p-5 border border-white/20">
            <div className="flex items-center gap-3 mb-3">
              <span className="text-2xl">🎯</span>
              <h2 className="text-white font-semibold text-lg">Our Mission</h2>
            </div>
            <p className="text-white/80 text-sm leading-relaxed">
              We believe everyone deserves access to high-quality exam
              preparation. Quizethic AI uses advanced artificial intelligence to
              create personalized quizzes that adapt to your learning style and
              help you master any topic efficiently.
            </p>
          </div>
        </section>

        {/* Features Grid */}
        <section className="mb-6">
          <h2 className="text-white font-semibold text-lg mb-4">
            What Makes Us Different
          </h2>
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-white/15 backdrop-blur-md rounded-xl p-4 border border-white/20">
              <span className="text-2xl mb-2 block">🤖</span>
              <h3 className="text-white font-medium text-sm mb-1">
                AI-Powered
              </h3>
              <p className="text-white/70 text-xs leading-relaxed">
                Questions generated by advanced AI for any topic
              </p>
            </div>
            <div className="bg-white/15 backdrop-blur-md rounded-xl p-4 border border-white/20">
              <span className="text-2xl mb-2 block">🌍</span>
              <h3 className="text-white font-medium text-sm mb-1">
                Global Exams
              </h3>
              <p className="text-white/70 text-xs leading-relaxed">
                UPSC, JEE, SAT, GRE, GAOKAO & more
              </p>
            </div>
            <div className="bg-white/15 backdrop-blur-md rounded-xl p-4 border border-white/20">
              <span className="text-2xl mb-2 block">📊</span>
              <h3 className="text-white font-medium text-sm mb-1">
                Adaptive
              </h3>
              <p className="text-white/70 text-xs leading-relaxed">
                Difficulty adjusts to your skill level
              </p>
            </div>
            <div className="bg-white/15 backdrop-blur-md rounded-xl p-4 border border-white/20">
              <span className="text-2xl mb-2 block">⚡</span>
              <h3 className="text-white font-medium text-sm mb-1">
                Instant
              </h3>
              <p className="text-white/70 text-xs leading-relaxed">
                Create quizzes in seconds, not hours
              </p>
            </div>
          </div>
        </section>

        {/* Team Section */}
        <section className="mb-6">
          <div className="bg-white/15 backdrop-blur-md rounded-2xl p-5 border border-white/20">
            <div className="flex items-center gap-3 mb-3">
              <span className="text-2xl">👥</span>
              <h2 className="text-white font-semibold text-lg">Our Team</h2>
            </div>
            <p className="text-white/80 text-sm leading-relaxed mb-4">
              We're a passionate team of educators, engineers, and AI
              researchers dedicated to revolutionizing how people prepare for
              exams worldwide.
            </p>
            <div className="flex items-center gap-2">
              <span className="text-xs text-white/60">Built with</span>
              <span className="text-red-400">❤️</span>
              <span className="text-xs text-white/60">for learners everywhere</span>
            </div>
          </div>
        </section>

        {/* Contact */}
        <section className="mb-8">
          <div className="bg-gradient-to-r from-pink-500/30 to-purple-500/30 backdrop-blur-md rounded-2xl p-5 border border-white/20">
            <h2 className="text-white font-semibold text-lg mb-2">
              Get in Touch
            </h2>
            <p className="text-white/80 text-sm mb-4">
              Have questions or feedback? We'd love to hear from you!
            </p>
            <a
              href="mailto:hello@quizethic.ai"
              className="inline-flex items-center gap-2 bg-white/20 px-4 py-2 rounded-full text-white text-sm font-medium hover:bg-white/30 transition-colors"
            >
              <svg
                className="w-4 h-4"
                fill="none"
                stroke="currentColor"
                strokeWidth={2}
                viewBox="0 0 24 24"
              >
                <path d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              hello@quizethic.ai
            </a>
          </div>
        </section>

        {/* Back to Home */}
        <button
          onClick={() => navigate("/")}
          className="w-full bg-white/20 backdrop-blur-md text-white font-semibold py-4 rounded-2xl border border-white/30 active:scale-[0.98] transition-transform"
        >
          Back to Home
        </button>
      </main>
    </div>
  );
};

export default About;

